package com.hbm.items.machine;

import com.hbm.items.ItemBase;
import com.hbm.items.ModItems;
import com.hbm.util.I18nUtil;
import net.minecraft.ChatFormatting;
import net.minecraft.core.component.DataComponents;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResultHolder;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.item.component.CustomData;
import net.minecraft.world.level.Level;

import javax.annotation.Nullable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

public class ItemRTGPellet extends ItemBase {

    private final short heat;
    private boolean doesDecay = false;
    private ItemStack decayItem = ItemStack.EMPTY;
    private long halflife = 0;
    private long lifespan = 0;

    public static final Map<ItemRTGPellet, ItemStack> pelletMap = new HashMap<>();

    public ItemRTGPellet(int heatIn) {
        super(new Properties().stacksTo(1));
        this.heat = (short) heatIn;
    }

    private static final String[] facts = new String[] {
            "One gram of Pu-238 costs $8,000.",
            "One gram of Pu-238 produces just under half a Watt of decay heat.",
            "The typical plutonium RTG contains close to eight kilograms of Pu-238.",
            "Pu-238's half life is 87.7 years.",
            "A plutonium RTG was used to power the New Horizons probe that visited Pluto in 2015.",
            "Po-210 can also be used for RTGs as it generates 140 W/g of decay heat due to its 138 day half life.",
            "Pa-231 is an isotope of protactinium that easily fissions, but it isn't quite fissile.",
            "Muons generated by matter-antimatter reactions can trigger nuclear fusion reactions at room temperature.",
            "Roughly 20% of U-235 nuclei will fail to fission when hit by a neutron. They become U-236 nuclei instead.",
            "Thorium reactors are really uranium reactors that convert thorium into U-233.",
            "Natural uranium consists of 99.284% U-238, 0.711% U-235, and 0.0055% U-234.",
            "Most nuclear reactors use uranium that has been enriched to 3-5% U-235.",
            "Uranium-based nuclear weapons require uranium enriched to at least 85-90% U-235.",
            "Depleted uranium is uranium that has had most of its U-235 removed. It is effectively pure U-238.",
            "In the 1920s, uranium was considered a useless byproduct of the production of radium.",
            "The Manhattan Project referred to refined natural uranium as tuballoy, enriched uranium as oralloy, and depleted uranium as depletalloy."
    };

    public ItemRTGPellet setDecays(ItemStack decayItem, long halflife, int halflifes) {
        this.doesDecay = true;
        this.decayItem = decayItem;
        this.halflife = halflife;
        this.lifespan = halflife * halflifes;
        pelletMap.put(this, decayItem);
        return this;
    }

    public long getMaxLifespan() {
        return this.lifespan;
    }

    public long getHalfLife() {
        return this.halflife;
    }

    public short getHeat() {
        return this.heat;
    }

    public ItemStack getDecayItem() {
        return decayItem.isEmpty() ? ItemStack.EMPTY : decayItem.copy();
    }

    public boolean getDoesDecay() {
        return this.doesDecay;
    }

    public static ItemStack handleDecay(ItemStack stack, ItemRTGPellet instance) {
        if (instance.getDoesDecay()) {
            if (instance.getLifespan(stack) <= 0)
                return instance.getDecayItem();
            else
                instance.decay(stack);
        }
        return stack;
    }

    public void decay(ItemStack stack) {
        if (stack != null && stack.getItem() instanceof ItemRTGPellet) {
            if (!((ItemRTGPellet) stack.getItem()).getDoesDecay())
                return;
            long cur = getLifespan(stack);
            setLifespan(stack, cur - 1);
        }
    }

    public long getLifespan(ItemStack stack) {
        if (stack != null && stack.getItem() instanceof ItemRTGPellet) {
            CustomData customData = stack.get(DataComponents.CUSTOM_DATA);
            if (customData != null && customData.contains("PELLET_DEPLETION")) {
                return customData.copyTag().getLong("PELLET_DEPLETION");
            }
            return getMaxLifespan();
        }
        return 0;
    }

    public void setLifespan(ItemStack stack, long lifespan) {
        CustomData.update(DataComponents.CUSTOM_DATA, stack, tag -> tag.putLong("PELLET_DEPLETION", lifespan));
    }

    public static double getDecay(ItemRTGPellet fuel, ItemStack stack) {
        if (fuel.getHalfLife() <= 0) return 1.0D;
        return Math.pow(0.5, ((double) (fuel.getMaxLifespan() - fuel.getLifespan(stack)) / (double) fuel.getHalfLife()));
    }

    public static short getScaledPower(ItemRTGPellet fuel, ItemStack stack) {
        return (short) Math.ceil(fuel.getHeat() * getDecay(fuel, stack));
    }

    @Override
    public InteractionResultHolder<ItemStack> use(Level world, Player player, InteractionHand hand) {
        if (!world.isClientSide()) {
            Random rand = new Random();
            player.displayClientMessage(Component.literal(facts[rand.nextInt(facts.length)]).withStyle(ChatFormatting.YELLOW), false);
        }
        return super.use(world, player, hand);
    }

    @Override
    public boolean isBarVisible(ItemStack stack) {
        return getDoesDecay() && getLifespan(stack) != getMaxLifespan();
    }

    @Override
    public int getBarWidth(ItemStack stack) {
        return Math.round((float) (1.0D - getDurabilityForDisplay(stack)) * 13.0F);
    }

    public double getDurabilityForDisplay(ItemStack stack) {
        final ItemRTGPellet instance = (ItemRTGPellet) stack.getItem();
        return 1D - getDecay(instance, stack);
    }

    @Override
    public void appendHoverText(ItemStack stack, TooltipContext context, List<Component> list, TooltipFlag flagIn) {
        final ItemRTGPellet instance = (ItemRTGPellet) stack.getItem();
        list.add(Component.literal("§c" + I18nUtil.resolveKey("desc.item.rtgHeat", getScaledPower(instance, stack)) + "§r"));
        if (instance.getDoesDecay()) {
            list.add(Component.literal("§aFuel left: " + ((int) (instance.getDecay(instance, stack) * 100000000D)) / 1000000D + "%§r"));
            list.add(Component.literal(I18nUtil.resolveKey("desc.item.rtgDecay", instance.getDecayItem().getHoverName().getString())));
            list.add(Component.literal(""));
            list.add(Component.literal(String.format("%s / %s ticks", instance.getLifespan(stack), instance.getMaxLifespan())));
        }
    }
}
